// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imimuptpqskxemqojvdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltaW11cHRwcXNreGVtcW9qdmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3OTMwNzQsImV4cCI6MjA3MjM2OTA3NH0.j8VsU2WvuyX6RD64Bc0-KssDWM-ImBp42MZKJGgM_rA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});